# .pages.yml — Pages CMS config for: team, courses, lessons, teachers, customers, infopages, posts
# Images live under: src/images (picker starts at this root)

media:
  name: images
  label: Images
  input: src/images
  output: src/images
  path: ""              # start at /src/images
  extensions: [png, jpg, jpeg, webp, svg]

settings:
  content:
    merge: true

content:
  # ---------------------
  # TEAM
  # ---------------------
  - name: team
    label: Team
    type: collection
    path: src/content/team
    filename: "{primary}.md"
    view:
      primary: name
      fields: [name, role]
      sort: [name]
    fields:
      - { name: name, label: Name, type: string, required: true }
      - { name: role, label: Role, type: string }
      - { name: bio,  label: Bio,  type: text }
      - name: image
        label: Image
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images } }
          - { name: alt, label: Alt text, type: string }
      - name: socials
        label: Socials
        type: object
        fields:
          - { name: twitter,  label: Twitter,  type: string }
          - { name: website,  label: Website,  type: string }
          - { name: linkedin, label: LinkedIn, type: string }
          - { name: email,    label: Email,    type: string }
      - { name: body, label: Body, type: rich-text }

  # ---------------------
  # COURSES
  # ---------------------
  - name: courses
    label: Courses
    type: collection
    path: src/content/courses
    filename: "{primary}.md"
    view:
      primary: title
      fields: [title, teacher, price]
      sort: [pubDate]
      default: { sort: pubDate, order: desc }
    fields:
      - { name: title,       label: Title, type: string, required: true }
      - { name: description, label: Description, type: text }
      - { name: pubDate,     label: Publication Date, type: date }
      - { name: teacher,     label: Teacher, type: string }
      - { name: duration,    label: Duration, type: string }
      - { name: videoUrl,    label: Video URL, type: string }
      - { name: price,       label: Price, type: number }
      - name: skills
        label: Skills
        type: string
        list: true
      - name: sections
        label: Sections
        type: object
        list: true
        fields:
          - { name: title,   label: Title,   type: string }
          - name: lessons
            label: Lessons
            type: string
            list: true
      - name: image
        label: Cover Image
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images } }
          - { name: alt, label: Alt text, type: string }
      - { name: tags,       label: Tags, type: string, list: true }
      - { name: isFeatured, label: Featured, type: boolean }
      - { name: isFree,     label: Free, type: boolean }
      - { name: isNew,      label: New, type: boolean }
      - { name: isLocked,   label: Locked, type: boolean }
      - { name: body,       label: Body, type: rich-text }

  # ---------------------
  # LESSONS (content type)
  # ---------------------
  - name: lessons
    label: Lessons
    type: collection
    path: src/content/lessons
    filename: "{primary}.md"
    view:
      primary: title
      fields: [title, course, section]
      sort: [title]
    fields:
      - { name: title,    label: Title, type: string, required: true }
      - { name: duration, label: Duration, type: string }
      - { name: videoUrl, label: Video URL, type: string }
      - { name: course,   label: Course, type: string }
      - { name: section,  label: Section, type: string }
      - { name: isLocked, label: Locked, type: boolean }
      - { name: body,     label: Body, type: rich-text }

  # ---------------------
  # TEACHERS
  # ---------------------
  - name: teachers
    label: Teachers
    type: collection
    path: src/content/teachers
    filename: "{primary}.md"
    view:
      primary: name
      fields: [name, role]
      sort: [name]
    fields:
      - { name: name, label: Name, type: string, required: true }
      - { name: role, label: Role, type: string }
      - { name: org,  label: Organization, type: string }
      - { name: bio,  label: Bio, type: text }
      - name: image
        label: Image
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images } }
          - { name: alt, label: Alt text, type: string }
      - name: socials
        label: Socials
        type: object
        fields:
          - { name: twitter,  label: Twitter,  type: string }
          - { name: linkedin, label: LinkedIn, type: string }
          - { name: website,  label: Website,  type: string }
      - { name: body, label: Body, type: rich-text }

  # ---------------------
  # CUSTOMERS
  # ---------------------
  - name: customers
    label: Customers
    type: collection
    path: src/content/customers
    filename: "{primary}.md"
    view:
      primary: name
      fields: [name, course]
      sort: [name]
    fields:
      - { name: name,   label: Name, type: string, required: true }
      - name: avatar
        label: Avatar
        type: object
        fields:
          # Schema uses string for url, but we can still use image picker; it writes a string path.
          - { name: url, label: Image, type: image, options: { media: images } }
          - { name: alt, label: Alt text, type: string }
      - { name: location,   label: Location,   type: string }
      - { name: occupation, label: Occupation, type: string }
      - { name: course,     label: Course,     type: string }
      - { name: quote,      label: Quote,      type: text }
      - { name: testimonial,label: Testimonial,type: rich-text }
      - { name: body,       label: Body, type: rich-text }

  # ---------------------
  # INFO PAGES
  # ---------------------
  - name: infopages
    label: Info Pages
    type: collection
    path: src/content/infopages
    filename: "{primary}.md"
    view:
      primary: page
    fields:
      - { name: page,    label: Page, type: string, required: true }
      - { name: pubDate, label: Publication Date, type: date }
      - { name: body,    label: Body, type: rich-text }

  # ---------------------
  # POSTS
  # ---------------------
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    filename: "{year}{month}{day}-{hour}{minute}{second}.md"
    view:
      primary: title
      fields: [title, pubDate, team]
      sort: [pubDate]
      default: { sort: pubDate, order: desc }
    fields:
      - { name: title,       label: Title, type: string, required: true }
      - { name: pubDate,     label: Publication Date, type: date }
      - { name: description, label: Description, type: text }
      - { name: team,        label: Team, type: string }
      - name: image
        label: Cover Image
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images } }
          - { name: alt, label: Alt text, type: string }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }
